// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/80060c94ef549c077a011977c2b5461bd0fd8947/striptags/index.d.ts
declare module 'striptags' {
    export default function strip (html: string, allowedTags?: string | string[]): string;
}
